version: "3.9"

services:
  soda_sql_tutorial_db:
    image: postgres
    container_name: soda_sql_tutorial_db
    environment:
      POSTGRES_USER: sodasql
      POSTGRES_DB: sodasql_tutorial
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/data

  soda_sql_project:
    build:
      context: .
      dockerfile: ./Dockerfile_soda_sql
    container_name: soda_sql_project
    volumes:
      - ./workspace:/workspace
    #tty: true
    ports:
      - 8001:5432
    links:
      - soda_sql_tutorial_db:soda_sql_tutorial_db
    depends_on:
      - soda_sql_tutorial_db
