version: "3.9"

services:
  soda_sql_tutorial_db:
    image: postgres
    environment:
      POSTGRES_USER: sodasql
      POSTGRES_DB: sodasql_tutorial
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 8000:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/data
